# Generated by Django 4.2 on 2024-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_genre', models.CharField(max_length=30)),
                ('movie_director', models.CharField(max_length=60)),
                ('release_year', models.IntegerField(default=2000)),
                ('synopsis', models.CharField(max_length=200)),
            ],
        ),
    ]
